### ISSUE TITLE
部署的问题

### ISSUE THREAD

**Issue by chiron688** [ATQQ/easypicker2-client#10]
大佬你好，很荣幸能见到如此优秀的项目
但是我在部署的过程中遇到了很多的问题，我是根据csdn上的一个文章进行部署的，具体网址如下：
https://blog.csdn.net/zhCSDA/article/details/122827861
（因为github网站抽风，挂了富强，我也还是无法上传详细截图，劳烦大佬阅读这么多字了）
首先是因为宝塔官方的更新，nodejs项目的创建并不完全一样，需绑定域名访问，但是域名绑定了，又无法创建新的网站目录，无限套娃（这个应该小问题）

但是部署过程中发现并没有占用到端口3000和5000，也就是说我依靠端口访问并不能访问到前端，会显示无法处理请求（最主要的）

而且因为您升级client项目的时候，前端文件dist删除了，所以无法确保是不是dist里面的脚本占用5000端口（其次主要的）

因为部署过程中的种种问题，我将redis端口换成了6380，不知道会不会因为这样导致脚本无法识别从而使项目不能运行

因为本人的打扰到您非常不好意思，但是也因为不能部署到如此优秀的项目而深感遗憾，希望大佬能解决我的疑惑。

**Comment by ATQQ** [comment]
收到，最近比较忙

争取这周抽时间写个手把手的部署教程

关于你提到的问题
1: dist目录是 build后生成的，不属于源码
2: 后端相关的配置我都暴露到了.env文件里，环境变量的意义，我都加了注释，详细看这https://github.com/ATQQ/easypicker2-server/blob/master/src/types/env.d.ts


首先你可以现在本地跑了再走线上部署流程

**Comment by ATQQ** [comment]
刚建了个QQ小群，方便可以加入及时交流沟通问题: 685446473
![qrcode_1647267266515](https://user-images.githubusercontent.com/42485491/158194299-9b36912a-4e1f-432a-9ff5-057c2b74e1f6.jpg)

**Comment by ATQQ** [comment]
手把手文档 ：https://docs.ep.sugarat.top/
